### ISSUE TITLE
Ventilation for Cooling of the filament at 100%.

### ISSUE THREAD

**Issue by Magiquall** [bigtreetech/BIGTREETECH-SKR-V1.3#518]
I just received my SKR 1.4 Turbo and I just implanted it in my Hypercube which worked before with an MKS SGEN L.

I have several concerns, but one worries me. The cooling ventilation of the filament is at full blast all the time. I can't cut it from the screen let alone vary it.

As I am still working on the Marlin firmware, would you have to check a parameter before saying that the card has a fault.
A marlin parameter or a other try for see if the output of this FAN0 is not damaged.

Thank you

**Comment by radek8** [comment]
Good day
which connector did you use for the cooling fan?

**Comment by Magiquall** [comment]
Hello.

I connect the cooling fan to FAN0

**Comment by radek8** [comment]
The FAN0 connector is the correct connector.
If the fan does not use the speed or shuts down, there will be a problem with the SKR board.
The switching transistor or pin P2.03 of the processor may be defective.
If you dare to solder SMS components, you can measure with a voltmeter where the problem is. if there is a problem with the transistor, you can replace it.

However, if you do not use the output on the HE1 hotend, you can remap the pin definition and use the HE1 to switch the cooling transistor.

If HE1 is not free, you can buy an external mofset and use one of the free pins that the PWM handles to control the cooling fan.

There are several options to correct the problem, it depends on you which one you choose :-)

Or you can claim the board to the supplier.

**Comment by radek8** [comment]
The FAN0 connector is the correct connector.
If the fan does not use the speed or shuts down, there will be a problem with the SKR board.
The switching transistor or pin P2.03 of the processor may be defective.
If you dare to solder SMS components, you can measure with a voltmeter where the problem is. if there is a problem with the transistor, you can replace it.

However, if you do not use the output on the HE1 hotend, you can remap the pin definition and use the HE1 to switch the cooling transistor.

If HE1 is not free, you can buy an external mofset and use one of the free pins that the PWM handles to control the cooling fan.

There are several options to correct the problem, it depends on you which one you choose :-)

Or you can claim the board to the supplier.

**Comment by Magiquall** [comment]
Hello, 
The card is new, so I'm making a return, thanks for the information. 

I tried putting the fan on FAN1, for the e1 hotend, but it was running full too, but I didn't redirect the pins, so it might be normal.

**Comment by radek8** [comment]
Attention. The FAN1 connector is still connected to the power supply. Therefore, it cannot be regulated or switched off

**Comment by radek8** [comment]
I still ask, did you define the SKR V1.4 board in Marlin correctly?

#define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO

**Comment by Magiquall** [comment]
Yes of course😉

**Comment by Magiquall** [comment]
> Attention. The FAN1 connector is still connected to the power supply. Therefore, it cannot be regulated or switched off


This is what I understood too, my English is very limited, but it seemed to me that only the FAN0 was with PWM.
