### ISSUE TITLE
Strange layershifts

### ISSUE THREAD

**Issue by Magnum8101** [bigtreetech/BIGTREETECH-SKR-V1.3#550]
I got some strange layershifts egen connecting SKR 1.4 T to my Anet A8. With original motherboard the prints get just fine.
I have tried 2 different turbo boards, 5 cheap TMC2209 steppers, and last try, BTTs TMC2208, but with similiar issues. Last try i did not tune the stepmotors. I am starting to give Up a silent printer with BTT SKR. 😔
![20211108_004903](https://user-images.githubusercontent.com/59516973/140693851-926be4b2-14ba-449d-9d5b-deac2a0cd6f5.jpg)
![20211015_135236](https://user-images.githubusercontent.com/59516973/140693866-4535814c-418c-4713-ae50-2730187744b0.jpg)

**Comment by AFactor2** [comment]
have you looked at the driver setup and micro stepping?I have several A8 units all on OE boards a BTT is a bit of a over kill for that machine id the r something you are looking to achieve? I have one from about 2013 and it has TL board's on X and Y, Dual PSU and MOS fet and i fixed the Z and the loos liner rods it prints ABS all day at 0.12 x 0.2 by 30mm SECSincerelyAndrey ***@***.***: This e-mail, including its contents and attachments, if any,are confidential.If you are not the named recipient please notify the sender and immediately delete it. You may not disseminate, distribute, or forward this e-mail message or disclose its contents to anyone else.   E-mail transmission cannot be guaranteed to be secure or error-free. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission. We make no representation or warranty as to the absence of viruses in this e-mail or any attachments. For the protection of our clients and our business, we may monitor and read e-mails sent to and from our server(s).


-------- Original Message --------
Subject: [bigtreetech/BIGTREETECH-SKR-V1.3] Strange layershifts (Issue
#550)
From: Magnum8101 ***@***.***>
Date: Mon, November 08, 2021 1:24 am
To: "bigtreetech/BIGTREETECH-SKR-V1.3"
***@***.***>
Cc: Subscribed ***@***.***>

 I got some strange layershifts egen connecting SKR 1.4 T to my Anet A8. With original motherboard the prints get just fine. I have tried 2 different turbo boards, 5 cheap TMC2209 steppers, and last try, BTTs TMC2208, but with similiar issues. Last try i did not tune the stepmotors. I am starting tonä give Up a silent printer with BTT SKR. 😔   —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Magnum8101** [comment]
Du you have a Good guide for driver setup and micro stepping? What i want to achive is furst of all a silent 3d printer, better Interface with touch screen etc.

**Comment by radek8** [comment]
Send configuration.. Send a photo of the jempers set up under the stepper controllers

**Comment by radek8** [comment]
What kind of step engines do you use?

**Comment by Magnum8101** [comment]
I use original enginges from Anet.
![20211110_212951](https://user-images.githubusercontent.com/59516973/141188699-f9fb1ada-7a49-4d81-9d8b-26f47a0a1321.jpg)

And here is my jumper setup, it is the same under all drivers
![20211110_212407](https://user-images.githubusercontent.com/59516973/141188514-21f13415-3528-4325-9d87-fe6d95eba332.jpg)
 
I did renamed the files from .h to .txt

[Configuration.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/7515721/Configuration.txt)
[Configuration_adv.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/files/7515722/Configuration_adv.txt)

**Comment by radek8** [comment]
Please take a picture of the TMC2209 driver from the bottom (from the pin side)
Or TMC2208, depending on what you want to use ...
You have TMC2208 in your configuration.

**Comment by Magnum8101** [comment]
I am now using TMC2208s now...
![Uploading 20211110_213559.jpg…]()

**Comment by Magnum8101** [comment]
I am now using 2208s
![20211110_213559](https://user-images.githubusercontent.com/59516973/141193969-ae78703e-89da-4d62-af3e-58d5a0b66839.jpg)

**Comment by radek8** [comment]
I see a problem here. The TMC 2208 drivers are not in UART mode.
You have to solder the two pins.

![image](https://user-images.githubusercontent.com/46979052/141200072-4d2414ea-51a2-4fed-b945-25529410768d.png)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/141200281-61ae18ba-636f-4c90-9ff0-6adad39ddc41.png)

**Comment by radek8** [comment]
I would also set a higher current in the motour configuration, you currently have 580mA
Set 650mA. If it doesn't get too hot, you can go up to 800mA, but always check if it's not warming up,

**Comment by radek8** [comment]
You only have HYBRID_THRESHOLD set to 45 mm / s.
I would set more, otherwise you won't enjoy the silent mode much :-)

**Comment by radek8** [comment]
Some news?

**Comment by Magnum8101** [comment]
Yeah! Now it is mutch better! Thank you very mutch! I connected these jumpers, with a waaaay to big soldering iron.
the 2208s are getting very hot, and so are my motors also. I turned down from 800mA to 700mA, maby I have to go lower.

**Comment by radek8** [comment]
I wrote that you can set the current on the 650mA motor and if it does not heat up, gradually add.
Setting the high value immediately and then removing it can damage the motor or motor controller.

Set the current value so that it is only slightly warm after an hour of printing.
The 2209 drivers are better than the 2208 and heat up less.
If you have them too, use them. You will need to change the parameter in the configuration and can also modify the jumper on the 2209 drivers.

**Comment by radek8** [comment]
What source do you use? According to the configuration do you have 12V power supply?

**Comment by Magnum8101** [comment]
My motors should have 800mA on paper. but I will have to try lower Current now. My power supply is 12V.
The TMC2209 is cheap ones i ordered, someone called the "dummy" stepper. There are no jumpers i can sold on them.

**Comment by radek8** [comment]
Send a photo to TMC2209
From both sides

**Comment by radek8** [comment]
Power supply 12V :-(

**Comment by Magnum8101** [comment]
Thank you very much for your help! I am closing this thread.
